#!/bin/bash


if [ "$#" -lt 1 ]
then
  echo "Must provide arguments [runseries] optional: [outfile]"
  echo ""
  echo "[runseries] can be a glob pattern or single session folder, the"
  echo "idea here is to be able to process a series of runs together"
  echo ""
  exit 1
fi

if [ ! -f "rt.bashrc" ]
then
  echo "Use 'runme' after installing the noPAW platform"
  echo "to create the (missing) required file 'rt.bashrc'"
  echo ""
  echo "  - if you have already done this, you probably are"
  echo "    trying to use 'runme' outside the nopaw directory"
  exit  1
fi

_HOME=$(pwd)
SHPROFILE="$_HOME/rt.bashrc"
source $SHPROFILE

if [ "$#" -gt 1 ]
then
  echo "Doing as many"
  for RS in "$@"
  do
    lib/analyze-parser.py $RS
  done
else
  echo "Doing as 1"
  lib/analyze-parser.py $1
fi

