#!/bin/bash


if [ "$#" -lt 1 ]
then
  echo "Must provide arguments [runseries] optional: [outfile]"
  echo ""
  echo "[runseries] can be a glob pattern or single session folder, the"
  echo "idea here is to be able to process a series of runs together"
  echo ""
  exit 1
fi

if [ -z "$SHPROFILE" ]
then
  echo "Use 'analyzerun' after sourcing the file 'rt.bashrc' in PAW"
  echo "platform home directory. Note you must install the PAW"
  echo "platform first by running 'install.sh'"
fi

source $SHPROFILE

if [ "$#" -gt 1 ]
then
  for RS in "$@"
  do
    analyze-parser.py $RS
  done
else
  analyze-parser.py $1
fi

