#!/bin/bash


RUNNAME="$1"
SCALE="$2"
OPERATION="$3"
FLOW="$4"
PROJECT="bif112"

if [ "$#" -lt 3 ]
then
  echo "Must provide arguments [runname] [nreplicates] [\"read\"/\"write\"] optional: [datasize]"
  exit 1
fi

LAYFACTOR="42"
TESTHOME="/gpfs/alpine/bif112/proj-shared/nopaw"
NNODES=$(( 1 + ( SCALE / LAYFACTOR ) + ( SCALE % LAYFACTOR > 0 ) ))

SHPROFILE="$TESTHOME/rt.bashrc"
JOBHOME="$TESTHOME/sessions/$RUNNAME"
DBLOCATION="$JOBHOME/mongo"

mkdir -p "$JOBHOME"
mkdir -p "$DBLOCATION"
mkdir -p "$JOBHOME/executors"

submitcommand="bsub -o sessions/$RUNNAME/nopaw.out -e sessions/$RUNNAME/nopaw.err -J $RUNNAME -nnodes $NNODES -W 20 -P $PROJECT -env \"all, SHPROFILE=$SHPROFILE, ARGS=$JOBHOME*$DBLOCATION*$LAYFACTOR*$SCALE*$RUNNAME*$OPERATION\" lib/jobscript.lsf"

echo "Submitting job with this command:"
echo $submitcommand
eval $submitcommand
