#!/usr/bin/env python

from pawtools import parser

if __name__ == "__main__":
    args = parser.parse_args()
    if args.command == "workload":
        pass
    elif args.command == "verify":
        pass
    elif args.command == "analyze":
