#!/usr/bin/env python

from pawtools import get_parser, analyzer, verifier, workload

if __name__ == "__main__":

    parser = get_parser()
    args = parser.parse_args()

    if args.command == "workload":
        workload(args)

    elif args.command == "verify":
        verifier(args)

    elif args.command == "analyze":
        analyzer(args)
