#!/bin/bash

RUNNAME="$1"
OPERATION="$2"
NREPLICATES="$3"
DBHOST="0.0.0.0"
DBPORT="27017"
DBNAME="testdb"

if [ "$#" -lt 1 ]
then
  echo "Must provide arguments [runname] [operation] optional: [datasize]"
  exit 1
fi

if [ ! "$(ls -A sessions/$RUNNAME/mongo/socket/)" ]
then
  echo "No MongoDB socket found, database should be free"
  if [ -f "sessions/$RUNNAME/mongo/db/mongod.lock" ]
  then
    echo "Found 'mongod.lock', deleting"
    rm "sessions/$RUNNAME/mongo/db/mongod.lock"
  fi
  if [ -f "sessions/$RUNNAME/mongo/db/WiredTiger.lock" ]
  then
    echo "Found 'WiredTiger.lock', deleting"
    rm "sessions/$RUNNAME/mongo/db/WiredTiger.lock"
  fi
else
  echo "MongoDB socket found, database is not free"
  #echo "not quitting"
  echo "quitting without starting new mongod instance"
  exit 1
fi

launch_amongod sessions/$RUNNAME/mongo &
verify-entries.py $DBHOST $DBPORT $DBNAME $RUNNAME $OPERATION $NREPLICATES
expect -c "
  set timeout 15
  spawn lib/kill_amongod $RUNNAME
  expect \"*then?type??y*\"
  send \"y\r\"
  expect eof
"
sleep 8
