#!/bin/bash


DBPATH=$1
DBPORT=$2
LAUNCH=$3
VERBOSE=$4

# No usage help :(
# and a non-optimal arg structure
# --> (cannot use "LAUNCH" w/out giving port)

if [ -z "$DBPORT" ]
then
  DBPORT=27017
fi

if [ -z "$DBPATH" ]
then
  echo "Need to give a name for mongodb instance as script argument"
  exit 1
else
  if ! [ -z "`lsof -Pi :$DBPORT | grep $DBPORT`" ]
  then
    echo "Port $DBPORT is already in use, try giving a different port as second argument"
    exit 1
  fi
fi

echo "launch_amongod GOIGN TO MAKE DIR $DBPATH"
mkdir -p $DBPATH
mkdir $DBPATH/db
mkdir $DBPATH/socket

echo -e "net:\n   unixDomainSocket:\n      pathPrefix: $DBPATH/socket\n   bindIp: 0.0.0.0\n   port:   $DBPORT\n" > $DBPATH/db.cfg

if [ "$LAUNCH" = "--launch" ]
then
  # Not text sensitive here
  echo "got args: $DBPATH $DBPORT $LAUNCH"
  echo "no backgrounding"
  echo "a database starts `date +%Y/%m/%d-%H:%M:%S.%5N`"
  numactl --interleave=all mongod --dbpath $DBPATH/db/ --config $DBPATH/db.cfg $VERBOSE &> $DBPATH/db.log
  echo "a database stops `date +%Y/%m/%d-%H:%M:%S.%5N`"
# Maybe let verbose bleed through as "launch" if matches
else
  # Text sensitive output to parent process
  numactl --interleave=all mongod --dbpath $DBPATH/db/ --config $DBPATH/db.cfg &> $DBPATH/db.log & MPID="$!"
  echo $MPID
fi
